= KIT Data Manager Documentation - Indexing Service
v{version}, KIT Data Manager Development Team, {date}
:doctype: book
:icons: font
:source-highlighter: highlightjs
:highlightjs-theme: github
:toc: left
:toclevels: 4
:sectlinks:
:sectnums:

[introduction]
= RESTful API Description

== Introduction

In this documentation, the basics of the KIT Data Manager RESTful API of the Indexing Service are described. You will be guided through the first steps of 
register an XML/JSON Mapping schema and update it. 

This documentation assumes, that you have an instance of elasticsearch up and running on localhost port 9200. If the repository is running on another
host or port you should change hostname and/or port accordingly. Furthermore, the examples assume that you are using the repository without authentication
and authorization, which is provided by another service. If you plan to use this optional service, please refer to its documentation first to see how the 
examples in this documentation have to be modified in order to work with authentication. Typically, this should be achieved by simple adding an additional header
entry.

The example structure is identical for all examples below. Each example starts with a CURL command that can be run by copy&paste to your console/terminal window.
The second part shows the HTTP request sent to the server including arguments and required headers. Finally, the third block shows the response comming from the server.
In between, special characteristics of the calls are explained together with additional, optional arguments or alternative responses.

[NOTE]
For technical reasons, all metadata resources shown in the examples contain all fields, e.g. also empty lists or fields with value 'null'. You may ignore most of them
as long as they are not needed. Some of them will be assigned by the server, others remain empty or null as long as you don't assign any value to them. 
All fields mandatory at creation time are explained in the resource creation example.

== Mapping Registration
[[ChapterMappingRegistration]]
=== Mapping Registration and Management

In this first section, the handling of mapping resources is explained. It all starts with creating your first xml mapping resource. The model of a mapping schema record looks
like this:
[source,options="nowrap"]
----
{
  "mappingId" : "...",
  "mappingType" : "...",
  "acl" : [ {
    "id" : 1,
    "sid" : "...",
    "permission" : "..."
  } ],
  "mappingDocumentUri" : "...",
  "documentHash" : "..."
}
----
At least the following elements are expected to be provided by the user: 

[point]
- mappingId: A unique label for the schema.
- mappingType: The resource type must be assigned by the user. For XSD schemas this should be 'application/xml'

In addition, ACL may be useful to make schema editable by others. (This will be of interest while updating an existing schema)

=== Registering an XML Mapping

The following example shows the creation of the first xsd schema only providing mandatory fields mentioned above:
[source,options="nowrap"]
----
record-xml.json:
{
  "mappingId":"my_first_xsd",
  "mappingType":"GEMMA"
}
----
[source,options="nowrap"]
----
my_first_xsd4gemma.mapping:
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/product.schema.json",
  "title": "Simple Mapping",
  "description": "Data resource mapping from json",
  "type": "object",
  "properties":{
  "Publisher":{
   "path": "metadata.publisher.#text",
   "type": "string"
   },
   "Publication Date":{
   "path": "metadata.publisher.@publicationDate",
   "type": "string"
   }
  }
}
----
include::{snippets}/post-xml-mapping/curl-request.adoc[]

You can see, that most of the sent mapping record is empty. Only mappingId and mappingType are provided by the user. HTTP-wise the call looks as follows: 

include::{snippets}/post-xml-mapping/http-request.adoc[]

As Content-Type only 'application/json' is supported and should be provided. The other headers are typically set by the HTTP client. After validating the 
provided document, adding missing information where possible and persisting the created resource, the result is sent back to the user and will look that way:

include::{snippets}/post-xml-mapping/http-response.adoc[]

What you see is, that the metadata schema record looks different from the original document. All remaining elements received a value by the server. 
Furthermore, you'll find an ETag header with the current ETag of the resource. This value is returned by POST, GET and PUT calls and must be provided for 
all calls modifying the resource, e.g. POST, PUT and DELETE, in order to avoid conflicts.

=== Registering an JSON Mapping

Now we register a mapping for JSON documents. This looks quite similar:
[source,options="nowrap"]
----
record-json.json:
{
  "mappingId":"my_first_json",
  "mappingType":"GEMMA"
}
----
[source,options="nowrap"]
----
my_first_json4gemma.mapping:
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/product.schema.json",
  "title": "Simple Mapping",
  "description": "Data resource mapping from json",
  "type": "object",
  "properties":{
  "Publisher":{
   "path": "publisher",
   "type": "string"
   },
   "Publication Date":{
   "path": "publicationDate",
   "type": "string"
   }
  }
}
----
include::{snippets}/post-json-mapping/curl-request.adoc[]

You can see, that most of the sent mapping record is empty. Only mappingId and mappingType are provided by the user. HTTP-wise the call looks as follows: 

include::{snippets}/post-json-mapping/http-request.adoc[]

As Content-Type only 'application/json' is supported and should be provided. The other headers are typically set by the HTTP client. After validating the 
provided document, adding missing information where possible and persisting the created resource, the result is sent back to the user and will look that way:

include::{snippets}/post-json-mapping/http-response.adoc[]

What you see is, that the metadata schema record looks different from the original document. All remaining elements received a value by the server. 
Furthermore, you'll find an ETag header with the current ETag of the resource. This value is returned by POST, GET and PUT calls and must be provided for 
all calls modifying the resource, e.g. POST, PUT and DELETE, in order to avoid conflicts.

==== Getting a List of Mapping Records

Obtaining all accessible mapping records. 

include::{snippets}/get-all-mappings/curl-request.adoc[]

In the actual HTTP request there is nothing special. You just access the path of the resource using the base path.

include::{snippets}/get-all-mappings/http-request.adoc[]

As a result, you receive a list of metadata schema records. 

include::{snippets}/get-all-mappings/http-response.adoc[]

[NOTE]
The header contains the field 'Content-Range" which displays delivered indices and the maximum number of available schema records. 
If there are more than 20 schemata registered you have to provide page and/or size as additional query parameters.

- page: Number of the page you want to get **(starting with page 0)**
- size: Number of entries per page.

The modified HTTP request  with pagination looks like follows:

include::{snippets}/get-all-mappings-pagination/http-request.adoc[]

